//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bgce_timetracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN
    {
        public int userID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string password_salt { get; set; }
        public Nullable<System.DateTime> password_last_set { get; set; }
        public byte[] is_locked_out { get; set; }
        public byte[] is_password_expired { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
