//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bgce_timetracker.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class trackerEntities : DbContext
    {
        public trackerEntities()
            : base("name=trackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LOCATION> LOCATIONs { get; set; }
        public virtual DbSet<NOTIFICATION> NOTIFICATIONs { get; set; }
        public virtual DbSet<PAID_STAFF> PAID_STAFF { get; set; }
        public virtual DbSet<PAY_PERIOD> PAY_PERIOD { get; set; }
        public virtual DbSet<PTO_REQUEST> PTO_REQUEST { get; set; }
        public virtual DbSet<TIME_SHEET> TIME_SHEET { get; set; }
        public virtual DbSet<TIME_SHEET_ENTRY> TIME_SHEET_ENTRY { get; set; }
        public virtual DbSet<UNIT_DIRECTOR> UNIT_DIRECTOR { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
        public virtual DbSet<VOLUNTEER> VOLUNTEERs { get; set; }
        public virtual DbSet<PAID_STAFF_VIEW> PAID_STAFF_VIEW { get; set; }
        public virtual DbSet<UNIT_DIRECTOR_VIEW> UNIT_DIRECTOR_VIEW { get; set; }
        public virtual DbSet<VOLUNTEER_VIEW> VOLUNTEER_VIEW { get; set; }
        public virtual DbSet<LOGIN> LOGINs { get; set; }
    }
}
