//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bgce_timetracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTIFICATION
    {
        public int notifID { get; set; }
        public string recipients { get; set; }
        public string type { get; set; }
        public string trigger { get; set; }
        public string content { get; set; }
        public System.DateTime created_on { get; set; }
        public Nullable<int> user_recipient { get; set; }
        public Nullable<int> user_sender { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
    }
}
