//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bgce_timetracker.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class NOTIFICATION
    {
        [DisplayName("Notification ID")]
        public int notifID { get; set; }
        [DisplayName("Recipient(s)")]
        public string recipients { get; set; }
        [DisplayName("Type")]
        public string type { get; set; }
        [DisplayName("Triggered By")]
        public string trigger { get; set; }
        [DisplayName("Content")]
        public string content { get; set; }
        [DisplayName("Created On")]
        public System.DateTime created_on { get; set; }
        [DisplayName("Recipient User")]
        public Nullable<int> user_recipient { get; set; }
        [DisplayName("Sending User")]
        public Nullable<int> user_sender { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
    }
}
