//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bgce_timetracker.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class PAID_STAFF
    {
        public int emplID { get; set; }
        public Nullable<double> pto_accrual_rate { get; set; }
        public Nullable<double> max_pto_accrual { get; set; }
        public Nullable<double> total_pto_accrued { get; set; }
        public Nullable<double> pay_rate { get; set; }
        public string pay_schedule { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
