//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bgce_timetracker.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class PAY_PERIOD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAY_PERIOD()
        {
            this.TIME_SHEET = new HashSet<TIME_SHEET>();
        }
    
        public int ppID { get; set; }
        [DisplayName("Start Date")]
        public Nullable<System.DateTime> start_date { get; set; }
        [DisplayName("End Date")]
        public Nullable<System.DateTime> end_date { get; set; }
        [DisplayName("Active")]
        public bool active { get; set; }
        [DisplayName("Created On")]
        public System.DateTime created_on { get; set; }
        [DisplayName("Created By")]
        public string created_by { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIME_SHEET> TIME_SHEET { get; set; }
    }
}
