//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bgce_timetracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTO_REQUEST
    {
        public int requestID { get; set; }
        public int requested_by { get; set; }
        public Nullable<double> total_time_requested { get; set; }
        public System.DateTime requested_on { get; set; }
        public bool approved { get; set; }
        public Nullable<System.DateTime> approved_on { get; set; }
        public Nullable<int> approved_by { get; set; }
        public string comments { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
    }
}
