//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bgce_timetracker.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class UNIT_DIRECTOR
    {
        [DisplayName("Employee ID")]
        public int emplID { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
