//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bgce_timetracker.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.NOTIFICATIONs = new HashSet<NOTIFICATION>();
            this.NOTIFICATIONs1 = new HashSet<NOTIFICATION>();
            this.PTO_REQUEST = new HashSet<PTO_REQUEST>();
            this.PTO_REQUEST1 = new HashSet<PTO_REQUEST>();
            this.TIME_SHEET = new HashSet<TIME_SHEET>();
            this.TIME_SHEET1 = new HashSet<TIME_SHEET>();
            this.TIME_SHEET_ENTRY = new HashSet<TIME_SHEET_ENTRY>();
            this.USER1 = new HashSet<USER>();
        }

        [DisplayName("User ID")]
        public int userID { get; set; }
        [DisplayName("First name")]
        public string fname { get; set; }
        [DisplayName("Last name")]
        public string lname { get; set; }
        [DisplayName("Active")]
        public bool active { get; set; }
        [DisplayName("Start date")]
        public Nullable<System.DateTime> start_date { get; set; }
        [DisplayName("Created on")]
        public System.DateTime created_on { get; set; }
        [DisplayName("Created by")]
        public string created_by { get; set; }
        [DisplayName("Updated on")]
        public Nullable<System.DateTime> updated_on { get; set; }
        [DisplayName("Updated by")]
        public Nullable<System.DateTime> updated_by { get; set; }
        [DisplayName("Manager")]
        public Nullable<int> manager { get; set; }
        [DisplayName("Location")]
        public Nullable<int> location { get; set; }
        [DisplayName("Email")]
        public string email { get; set; }
        [DisplayName("Is administrator")]
        public bool is_administrator { get; set; }
        [DisplayName("User type")]
        public string user_type { get; set; }
        [DisplayName("Total hours worked")]
        public Nullable<double> total_hours_worked { get; set; }
        [DisplayName("Can work foodservice")]
        public bool can_work_foodservice { get; set; }
    
        public virtual LOCATION LOCATION1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTIFICATION> NOTIFICATIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTIFICATION> NOTIFICATIONs1 { get; set; }
        public virtual PAID_STAFF PAID_STAFF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PTO_REQUEST> PTO_REQUEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PTO_REQUEST> PTO_REQUEST1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIME_SHEET> TIME_SHEET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIME_SHEET> TIME_SHEET1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIME_SHEET_ENTRY> TIME_SHEET_ENTRY { get; set; }
        public virtual UNIT_DIRECTOR UNIT_DIRECTOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER> USER1 { get; set; }
        public virtual USER USER2 { get; set; }
        public virtual VOLUNTEER VOLUNTEER { get; set; }
        public virtual LOGIN LOGIN { get; set; }
    }
}
